version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cypherly-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    container_name: cypherly-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cypherly-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq
    container_name: cypherly-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_USER=${SEQ_USER}
      - SEQ_PASSWORD=${SEQ_PASSWORD}
    ports:
      - "5341:80"

volumes:
  db_data:
